baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Landscape'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'Capabilities'
pageRef = '/capabilities'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
